### ISSUE TITLE
Changing from 'Character' to 'numeric'

### ISSUE THREAD

**Issue by PanditPranav** [ecohealthalliance/eidith#44]
Following columns get downloaded as 'Character', instead of 'numeric'

events$latitude
events$longitude

```{r}
events = ed_events()
class(events$latitude)
```
[1] "character"

**Comment by noamross** [comment]
Thanks, @PanditPranav. I have updated this in the development branch.  This change also switches the order of long and lat, per @cmzambranat's request, so that it's easier to convert results to a `SpatialPointsDataFrame`.

The dev branch will be merged to master by the end of the month for the workshop.

**Comment by noamross** [comment]
Note that you'll have to run `ed_db_download()` after this update, because the fields are converted to numeric at the download stage.
