### ISSUE TITLE
Wet/dry season variable

### ISSUE THREAD

**Issue by jeliang** [ecohealthalliance/eidith#72]
Create a variable for wet/dry seasons in events table. 

Need dates from country liaisons (wet/dry season different in different countries)?

**Comment by arw36** [comment]
Why can't we remotely pull this based on rain - check with @eveskew as this was a component in the bat seasonality project?

**Comment by jeliang** [comment]
*Clarification: wet/dry season as defined for country _targets_

**Comment by eveskew** [comment]
If I'm understanding right, Janice is asking for a wet/dry season variable because teams had targets to sample a particular amount in each of those seasons in their country? In that case, I think her idea of just getting the wet/dry season date definitions from the countries themselves makes the most sense. If you want to create a wet/dry season variable strictly from rain data, we could also do that pretty easily, as Anna suggests.
